### ISSUE TITLE
ModuleNotFoundError: No module named 'django.contrib.contenttypes.generic'

### ISSUE THREAD

**Issue by VanDxtr** [divio/aldryn-newsblog#467]
[tiziano@localhost reseller365]$ python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe7ee5b9950>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/lib/python3.6/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/aldryn_newsblog/models.py", line 38, in <module>
    from taggit.managers import TaggableManager
  File "/usr/lib/python3.6/site-packages/taggit/managers.py", line 5, in <module>
    from django.contrib.contenttypes.generic import GenericRelation
ModuleNotFoundError: No module named 'django.contrib.contenttypes.generic'

**Comment by marksweb** [comment]
Are you trying to use django 1.11? I was looking at this recently & `taggit` doesn't seem to support 1.11 yet.

**Comment by mohanrao487** [comment]
I am using python 2.7.5 and django 1.11...trying to create simple hello w application.I am stuckup with the above error.Can you please help me.

**Comment by kinkerl** [comment]
can you go into more detail? i just now tried django 1.11.11.1 with newsblog 2.1.1 and it worked without problems

**Comment by vThaian** [comment]
I checked as @kinkerl on Django 1.11 and 2.2.1 and I don't have this issue. I'm closing because is old. If you have still problems feel free to ping me @VanDxtr.
